"""
AfterHours Sentinel - Configuration Module
All thresholds, position sizing parameters, API configurations, and safety constraints.
"""

import os
from typing import Dict, List, Any

# Auto-load local .env file if present
_env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
if os.path.exists(_env_path):
    try:
        with open(_env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    k, v = k.strip(), v.strip().strip('"').strip("'")
                    if k not in os.environ:
                        os.environ[k] = v
    except Exception:
        pass

# ==============================================================================
# NON-NEGOTIABLE SAFETY CONSTRAINTS
# ==============================================================================
# All order-placing functions default to dryRun=True.
# To enable actual demo order placement against Bitget Agent Hub Demo, set this to False.
DEFAULT_DRY_RUN: bool = True

# Enforce Demo Environment Only (Never mainnet/live)
DEMO_MODE: bool = True
PAPER_TRADING_FLAG: bool = True

# ==============================================================================
# BITGET AGENT HUB & DEMO CREDENTIALS (ENV + OAUTH PERSISTENCE SUPPORT)
# ==============================================================================
def load_bitget_credentials():
    """
    Loads Bitget API credentials with automatic fallback hierarchy:
    1. Direct Environment Variables (BITGET_DEMO_API_KEY / BITGET_API_KEY)
    2. Bitget Agentic OAuth Token Store (~/.bitget/oauth_token.json)
    3. Mock Fallback ('mock_demo_api_key')
    """
    env_key = os.getenv("BITGET_DEMO_API_KEY") or os.getenv("BITGET_API_KEY")
    env_secret = os.getenv("BITGET_DEMO_API_SECRET") or os.getenv("BITGET_SECRET_KEY")
    env_pass = os.getenv("BITGET_DEMO_PASSPHRASE") or os.getenv("BITGET_PASSPHRASE")

    if env_key and env_secret and env_pass:
        return env_key, env_secret, env_pass, "env_vars"

    # Check OAuth token file generated by bitget-agent-mcp / authorize_wait
    oauth_path = os.path.expanduser("~/.bitget/oauth_token.json")
    if os.path.exists(oauth_path):
        try:
            with open(oauth_path, "r", encoding="utf-8") as f:
                import json
                oauth_data = json.load(f)
                oauth_key = oauth_data.get("apiKey")
                oauth_secret = oauth_data.get("secretKey")
                oauth_pass = oauth_data.get("passphrase")
                if oauth_key and oauth_secret and oauth_pass:
                    return oauth_key, oauth_secret, oauth_pass, f"oauth_token_file [{oauth_path}]"
        except Exception:
            pass

    return (
        env_key or "mock_demo_api_key",
        env_secret or "mock_demo_secret",
        env_pass or "mock_demo_passphrase",
        "mock_fallback"
    )

_key, _secret, _pass, BITGET_CREDENTIALS_SOURCE = load_bitget_credentials()
BITGET_DEMO_API_KEY: str = _key
BITGET_DEMO_API_SECRET: str = _secret
BITGET_DEMO_PASSPHRASE: str = _pass

# Base URL for Bitget Agent Hub / Demo Trading API
BITGET_DEMO_BASE_URL: str = os.getenv("BITGET_DEMO_BASE_URL", "https://api.bitget.com")
BITGET_AGENT_HUB_URL: str = os.getenv("BITGET_AGENT_HUB_URL", "https://api.bitget.com/api/v2/mix/order/place-order")

# ==============================================================================
# GROQ LLM ANALYST CONFIGURATION (OpenAI-Compatible)
# ==============================================================================
GROQ_BASE_URL: str = os.getenv("GROQ_BASE_URL", "https://api.groq.com/openai/v1")
GROQ_API_KEY: str = os.getenv("GROQ_API_KEY", "mock_groq_key")
GROQ_MODEL: str = os.getenv("GROQ_MODEL", "qwen/qwen3.8-27b")

# ==============================================================================
# DIVERGENCE ENGINE THRESHOLDS & PARAMETERS
# ==============================================================================
BETA_ROLLING_WINDOW_DAYS: int = 30
RESIDUAL_ROLLING_WINDOW_DAYS: int = 30
Z_SCORE_THRESHOLD: float = 2.0
VOLUME_RATIO_WEAK_THRESHOLD: float = 0.5
VOLUME_RATIO_CONFIRMING_THRESHOLD: float = 0.8

# Defensive residual volatility floor (0.8% = 0.008 / 80 bps)
# NOTE: This is a defensive risk floor to prevent numerical zero-division artifacts
# during periods of compressed market volatility, rather than an empirical volatility estimate.
DEFENSIVE_VOLATILITY_FLOOR: float = 0.008
MIN_RESIDUAL_STDEV: float = DEFENSIVE_VOLATILITY_FLOOR

# Explicit event reaction window (minutes)
EVENT_REACTION_WINDOW_MINUTES: int = 30

# ==============================================================================
# RISK ENGINE PARAMETERS
# ==============================================================================
POSITION_SIZE_PCT: float = 0.03       # Fixed 3% of paper portfolio per trade
STOP_LOSS_PCT: float = 0.015          # Hard stop at 1.5% from entry price
TAKE_PROFIT_PCT: float = 0.03         # Target mean reversion take profit 3.0%
MAX_OPEN_POSITIONS: int = 2           # Max 2 simultaneous open positions
DAILY_LOSS_LIMIT_PCT: float = 0.02    # Daily loss limit 2% of portfolio - halt new trades

# Default paper portfolio initial balance
DEFAULT_PORTFOLIO_BALANCE_USD: float = 100_000.0

# ==============================================================================
# ASSET BENCHMARK MAPPINGS
# Tech / Semi rTokens map to QQQ, all other assets map to BTC
# ==============================================================================
TECH_SEMI_SYMBOLS: List[str] = [
    "NVDA", "AAPL", "MSFT", "GOOGL", "GOOG", "AMZN", "META",
    "TSLA", "AMD", "INTC", "AVGO", "QCOM", "ARM", "MU", "SMCI", "ASML",
    "PLTR", "COIN", "MSTR", "BABA", "NFLX"
]

BENCHMARK_TECH: str = "QQQ"
BENCHMARK_GENERAL: str = "BTC"

# Peer Tech Basket mapping for peer-relative beta calculations
PEER_TECH_BASKET: Dict[str, List[str]] = {
    "NVDA": ["AMD", "INTC", "QCOM", "AVGO", "TSM"],
    "TSLA": ["RIVN", "LCID", "F", "GM"],
    "AAPL": ["MSFT", "GOOGL", "AMZN", "META"],
    "MSFT": ["AAPL", "GOOGL", "AMZN", "META"],
    "GOOGL": ["MSFT", "AAPL", "META", "AMZN"],
    "AMZN": ["MSFT", "GOOGL", "AAPL", "META"],
    "META": ["GOOGL", "MSFT", "SNAP", "PINS"],
    "AMD": ["NVDA", "INTC", "QCOM", "AVGO"],
    "INTC": ["NVDA", "AMD", "QCOM", "AVGO"],
    "ARM": ["NVDA", "AMD", "QCOM", "AVGO", "INTC"],
    "PLTR": ["MSFT", "GOOGL", "AMZN", "SNOW", "AI"],
    "COIN": ["MSTR", "MARA", "RIOT", "HOOD"],
    "MSTR": ["COIN", "MARA", "RIOT", "CLSK"],
    "BABA": ["JD", "PDD", "BIDU", "TCEHY"],
    "NFLX": ["DIS", "WBD", "PARA", "AMZN"]
}

def get_benchmark_for_symbol(symbol: str) -> str:
    """Returns QQQ for tech/semi tickers, BTC for all other rTokens."""
    sym = symbol.upper().replace("-USDT", "").replace("USDT", "")
    if sym.startswith("R") and sym[1:] in TECH_SEMI_SYMBOLS:
        clean_sym = sym[1:]
    else:
        clean_sym = sym
    if clean_sym in TECH_SEMI_SYMBOLS:
        return BENCHMARK_TECH
    return BENCHMARK_GENERAL

# ==============================================================================
# EVENT LISTENER CONFIGURATION, TAXONOMY & FRESHNESS
# ==============================================================================
EVENT_FRESHNESS_WINDOW_HOURS: float = 4.0  # Max allowable age for news events (4 hours)

# Standardized 9-category event taxonomy
EVENT_TAXONOMY: List[str] = [
    "earnings",
    "macro",
    "regulatory",
    "tariff",
    "geopolitical",
    "product",
    "corporate",
    "analyst",
    "other"
]

EVENT_KEYWORDS: List[str] = [
    "tariff", "tariffs", "fed", "federal reserve", "rate decision", "interest rate",
    "fomc", "cpi", "ppi", "inflation", "earnings", "guidance", "revenue beat",
    "revenue miss", "eps", "profit warning", "sanctions", "geopolitical",
    "trade war", "antitrust", "sec investigation", "war", "embargo", "stimulus",
    "regulatory", "fda", "doj", "subpoena", "lawsuit", "patent", "recall",
    "upgrade", "downgrade", "price target", "merger", "acquisition", "restructuring"
]

# Logging paths
LOG_DIR: str = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logs")
TRADES_JSONL_LOG: str = os.path.join(LOG_DIR, "sentinel_trades.jsonl")
TRADES_LOG_FILE: str = TRADES_JSONL_LOG
TRADES_CSV_LOG: str = os.path.join(LOG_DIR, "sentinel_trades.csv")
SUPERVISOR_PID_FILE: str = os.path.join(LOG_DIR, "supervisor.pid")
LIVE_PID_FILE: str = os.path.join(LOG_DIR, "live.pid")

# Equity Ticker Metadata & Parameters (All 15 Single-Stock Bitget Demo Equities)
# NOTE: Betas are initial heuristic estimates against QQQ based on historical beta profiles,
# not empirical fits, matching the standard of the original 9 assets.
EQUITY_TICKER_MAP: Dict[str, Dict[str, Any]] = {
    "NVDA": {"name": "NVIDIA", "benchmark": "QQQ", "beta": 1.35},
    "TSLA": {"name": "Tesla", "benchmark": "QQQ", "beta": 1.45},
    "AAPL": {"name": "Apple", "benchmark": "QQQ", "beta": 1.05},
    "MSFT": {"name": "Microsoft", "benchmark": "QQQ", "beta": 1.15},
    "GOOGL": {"name": "Alphabet", "benchmark": "QQQ", "beta": 1.10},
    "AMZN": {"name": "Amazon", "benchmark": "QQQ", "beta": 1.20},
    "META": {"name": "Meta", "benchmark": "QQQ", "beta": 1.25},
    "AMD": {"name": "AMD", "benchmark": "QQQ", "beta": 1.40},
    "INTC": {"name": "Intel", "benchmark": "QQQ", "beta": 1.10},
    "ARM": {"name": "Arm Holdings", "benchmark": "QQQ", "beta": 1.55},
    "PLTR": {"name": "Palantir", "benchmark": "QQQ", "beta": 1.65},
    # --------------------------------------------------------------------------
    # Crypto-Correlated Equities (COIN, MSTR):
    # Architectural Benchmark Decision:
    # We assign 'QQQ' as their primary equity benchmark in EQUITY_TICKER_MAP
    # (with explicit 'secondary_benchmark': 'BTC' metadata).
    # Reasoning:
    # 1. Pipeline Parity: Keeps uniform equity beta calculations against the US market
    #    without modifying the 5-stage mathematical engine.
    # 2. Known Approximation Disclosure: While QQQ captures general tech risk appetite,
    #    COIN and MSTR are fundamentally driven by spot Bitcoin volatility. Documented
    #    explicitly as an approximation; their elevated initial betas (2.20 and 2.50)
    #    absorb this crypto-driven volatility against QQQ moves.
    # --------------------------------------------------------------------------
    "COIN": {"name": "Coinbase", "benchmark": "QQQ", "secondary_benchmark": "BTC", "beta": 2.20},
    "MSTR": {"name": "MicroStrategy", "benchmark": "QQQ", "secondary_benchmark": "BTC", "beta": 2.50},
    "BABA": {"name": "Alibaba", "benchmark": "QQQ", "beta": 0.95},
    "NFLX": {"name": "Netflix", "benchmark": "QQQ", "beta": 1.20}
}

